#file for develop purposes only
version: '2.2'
volumes:
  postgresql_data:
    external: false
  es_data01:
    driver: local

networks:
  filestorenet:
    driver: bridge

services:
  db:
    image: postgres:11
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jumysbar-db
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - filestorenet
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
    volumes:
      - es_data01:/usr/share/elasticsearch/data
    networks:
      - filestorenet
    ports:
      - 9200:9200
